site_name: ZbwCarRent
site_url: https://example.com
theme:
  name: material
  custom_dir: overrides
  logo: images/car-rental-logo.png
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode